version: 2.1

jobs:
  setup_and_run:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Setting up environment...
          command: |
            sudo apt-get update && sudo apt-get install -y gcc
            pip install telebot flask pymongo aiohttp python-telegram-bot
      - run:
          name: Compiling C++ file into binary...
          command: |
            g++ -o raja raja.cpp -std=c++11 -pthread || exit 1
            chmod +x raja
      - run:
          name: Running the compiled binary...
          command: |
            while true; do
              python3 d.py || { echo "Application crashed. Restarting..."; sleep 5; }
            done

  wait_and_restart:
    docker:
      - image: circleci/python:3.9
    steps:
      - run:
          name: Sleeping for 1 hour before restarting pipeline...
          command: sleep 3600
      - run:
          name: Restarting the pipeline...
          command: curl -X POST -F token=$CIRCLECI_TOKEN -F ref=$CIRCLE_BRANCH https://circleci.com/api/v2/project/$CIRCLE_PROJECT_SLUG/pipeline

workflows:
  version: 2
  build_and_restart:
    jobs:
      - setup_and_run
      - wait_and_restart:
          requires:
            - setup_and_run
