name: Build and Test

on: 
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install additional Python packages
        run: |
          pip install telebot flask pymongo aiohttp python-telegram-bot

      - name: Compile C++ file into binary
        run: |
          sudo apt-get update && sudo apt-get install -y g++
          g++ -o raja raja.cpp -std=c++11 -pthread || exit 1
      
      - name: Run d.py
        run: |
          while true; do
            python d.py || { echo "Application crashed. Restarting..."; sleep 5; }
          done
