  version: 2.1

  orbs:
  python: circleci/python@2.1.1

  jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install additional Python packages
          command: |
            pip install telebot flask pymongo aiohttp python-telegram-bot
      - run:
          name: Compiling C++ file into binary...
          command: |
            sudo apt-get update && sudo apt-get install -y g++
            g++ -o raja raja.cpp -std=c++11 -pthread || exit 1
      - run:
          name: Run d.py
          command: |
            while true; do
              python d.py || { echo "Application crashed. Restarting..."; sleep 5; }
            done

  workflows:
     version: 2
      build_and_run:
      jobs:
        - build-and-test
